// Code generated by strictspec. DO NOT EDIT.
//
// strictspec generator: 0.1.0
// schema:              strictcode-profile (format_version 1)
// regenerate:          strictspec gen --manifest strictspec.toml
//
// Released under the MIT license (unencumbered). This file is machine-generated;
// edit the schema and regenerate, never this file.
package profilespec

import "github.com/smm-h/strictspec/go/strictspec"

// GeneratedBy is the strictspec release that produced this file. The runtime
// pairing guard hard-errors unless it matches the linked runtime exactly.
const GeneratedBy = "0.1.0"

// SchemaFormatVersion is the document format_version this validator accepts.
const SchemaFormatVersion = 1

// embeddedSchema carries the compiled schema (and its imported type-definition
// files and scalar manifest) so the validator is self-contained and does no IO.
var embeddedSchema = map[string]string{
	"profile.schema.toml": `name = "strictcode-profile"
meta_version = 1
format_version = 1
document_syntax = "toml"
role = "schema"
root = "Profile"
targets = ["go"]
description = "Gates schema/profiles/*.toml: per-language construct mappings and capability statuses. node_kind/row_kind arms are SOURCED from schema/vocabulary.toml (strictspec decision 32) — vocabulary content changes surface here as baked-arm staleness."

[types.Profile]
type = "record"

[types.Profile.fields.language]
type = "enum"
required = true
values = ["py", "go", "ts"]

[types.Profile.fields.display_name]
type = "string"
required = true
non_empty = true

[types.Profile.fields.grammar]
type = "string"
required = true
regex = "^tree-sitter-[a-z0-9-]+$"

[types.Profile.fields.constructs]
type = "array"
required = true
min_len = 1
[types.Profile.fields.constructs.item]
type = "Construct"

[types.Profile.fields.capabilities]
type = "map"
required = true
key_pattern = "^[a-z][a-z0-9-]*$"
order = "incidental"
[types.Profile.fields.capabilities.value]
type = "CapabilityStatus"

[types.Construct]
type = "record"
[types.Construct.fields.construct]
type = "string"
required = true
non_empty = true

[types.Construct.fields.node_kind]
type = "enum"
required = false
description = "Sourced from the vocabulary; exactly one of node_kind/row_kind per construct."
[types.Construct.fields.node_kind.source]
document = "schema/vocabulary.toml"
selector = "node_kinds[].id"
baked = [
  "workspace_member",
  "module",
  "entry_point",
  "function",
  "closure",
  "type",
  "type_param",
  "variable",
  "endpoint",
  "db_entity",
]

[types.Construct.fields.row_kind]
type = "enum"
required = false
description = "Sourced from the vocabulary; exactly one of node_kind/row_kind per construct."
[types.Construct.fields.row_kind.source]
document = "schema/vocabulary.toml"
selector = "row_kinds[].id"
baked = [
  "imports",
  "declares_dependency",
  "exports",
  "resolves_to",
  "contains",
  "calls",
  "instantiates",
  "references",
  "conforms_to",
  "decorates",
  "validates",
  "accesses",
  "handled_by",
  "persists_to",
]

[types.Construct.fields.notes]
type = "string"
required = true
non_empty = true

[[types.Construct.constraints]]
form = "exactly-one-of"
fields = ["node_kind", "row_kind"]

[types.CapabilityStatus]
type = "record"
[types.CapabilityStatus.fields.status]
type = "enum"
required = true
values = ["supported", "planned", "not-applicable"]
[types.CapabilityStatus.fields.reason]
type = "string"
required = false
non_empty = true

[[types.CapabilityStatus.constraints]]
form = "conditional-required"
field = "reason"
when = { field = "status", predicate = "equals", value = "not-applicable" }

[[types.CapabilityStatus.constraints]]
form = "forbidden-when"
field = "reason"
when = { field = "status", predicate = "in", values = ["supported", "planned"] }
`,
}

const embeddedMainFile = "profile.schema.toml"

var program *strictspec.Program

func init() {
	// Version pairing: generated code and runtime must be the same release.
	strictspec.RequireRuntimeVersion(GeneratedBy)
	p, err := strictspec.CompileEmbedded(embeddedSchema, embeddedMainFile)
	if err != nil {
		panic(err)
	}
	program = p
}

// ValidateBytes is the raw-bytes entry point: lossless parse of input in the
// given syntax ("json" | "toml" | "jsonl"), then validate. It returns the
// typed root value (nil when any diagnostic fired) and the ordered diagnostics.
func ValidateBytes(input []byte, syntax string) (*Profile, []strictspec.Diagnostic) {
	res := program.Validate(input, syntax)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	v, err := strictspec.LoadValue(input, syntax)
	if err != nil {
		return nil, res.Diagnostics
	}
	return bindProfile(v), nil
}

// ValidateValue is the tagged-value entry point: validate an already-parsed
// tagged document value (from strictspec.LoadValue or a typed constructor).
func ValidateValue(v strictspec.Value) (*Profile, []strictspec.Diagnostic) {
	res := program.ValidateValue(v)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	return bindProfile(v), nil
}

// ValidateBytesWithEvidence is ValidateBytes plus cross-document resolver
// evidence for the phase-2 constraint vocabulary.
func ValidateBytesWithEvidence(input []byte, syntax string, evidence map[string][]map[string]any) (*Profile, []strictspec.Diagnostic) {
	res := program.ValidateWithEvidence(input, syntax, evidence)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	v, err := strictspec.LoadValue(input, syntax)
	if err != nil {
		return nil, res.Diagnostics
	}
	return bindProfile(v), nil
}

// Profile is the frozen typed binding of the "Profile" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type Profile struct {
	Language     string
	DisplayName  string
	Grammar      string
	Constructs   []*Construct
	Capabilities strictspec.Value
}

func bindProfile(v strictspec.Value) *Profile {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &Profile{}
	if fv, ok := v.Field("language"); ok {
		out.Language = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("display_name"); ok {
		out.DisplayName = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("grammar"); ok {
		out.Grammar = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("constructs"); ok {
		out.Constructs = bindSlice(fv, func(e strictspec.Value) *Construct { return bindConstruct(e) })
	}
	if fv, ok := v.Field("capabilities"); ok {
		out.Capabilities = fv
	}
	return out
}

// WithLanguage returns a copy of Profile with Language set to the given value.
func (x *Profile) WithLanguage(v string) *Profile {
	c := *x
	c.Language = v
	return &c
}

// WithDisplayName returns a copy of Profile with DisplayName set to the given value.
func (x *Profile) WithDisplayName(v string) *Profile {
	c := *x
	c.DisplayName = v
	return &c
}

// WithGrammar returns a copy of Profile with Grammar set to the given value.
func (x *Profile) WithGrammar(v string) *Profile {
	c := *x
	c.Grammar = v
	return &c
}

// WithConstructs returns a copy of Profile with Constructs set to the given value.
func (x *Profile) WithConstructs(v []*Construct) *Profile {
	c := *x
	c.Constructs = v
	return &c
}

// WithCapabilities returns a copy of Profile with Capabilities set to the given value.
func (x *Profile) WithCapabilities(v strictspec.Value) *Profile {
	c := *x
	c.Capabilities = v
	return &c
}

// Construct is the frozen typed binding of the "Construct" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type Construct struct {
	Construct string
	NodeKind  string
	RowKind   string
	Notes     string
}

func bindConstruct(v strictspec.Value) *Construct {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &Construct{}
	if fv, ok := v.Field("construct"); ok {
		out.Construct = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("node_kind"); ok {
		out.NodeKind = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("row_kind"); ok {
		out.RowKind = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("notes"); ok {
		out.Notes = func() string { r, _ := fv.AsString(); return r }()
	}
	return out
}

// WithConstruct returns a copy of Construct with Construct set to the given value.
func (x *Construct) WithConstruct(v string) *Construct {
	c := *x
	c.Construct = v
	return &c
}

// WithNodeKind returns a copy of Construct with NodeKind set to the given value.
func (x *Construct) WithNodeKind(v string) *Construct {
	c := *x
	c.NodeKind = v
	return &c
}

// WithRowKind returns a copy of Construct with RowKind set to the given value.
func (x *Construct) WithRowKind(v string) *Construct {
	c := *x
	c.RowKind = v
	return &c
}

// WithNotes returns a copy of Construct with Notes set to the given value.
func (x *Construct) WithNotes(v string) *Construct {
	c := *x
	c.Notes = v
	return &c
}

// CapabilityStatus is the frozen typed binding of the "CapabilityStatus" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type CapabilityStatus struct {
	Status string
	Reason string
}

func bindCapabilityStatus(v strictspec.Value) *CapabilityStatus {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &CapabilityStatus{}
	if fv, ok := v.Field("status"); ok {
		out.Status = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("reason"); ok {
		out.Reason = func() string { r, _ := fv.AsString(); return r }()
	}
	return out
}

// WithStatus returns a copy of CapabilityStatus with Status set to the given value.
func (x *CapabilityStatus) WithStatus(v string) *CapabilityStatus {
	c := *x
	c.Status = v
	return &c
}

// WithReason returns a copy of CapabilityStatus with Reason set to the given value.
func (x *CapabilityStatus) WithReason(v string) *CapabilityStatus {
	c := *x
	c.Reason = v
	return &c
}

func bindSlice[T any](v strictspec.Value, f func(strictspec.Value) T) []T {
	items := v.Items()
	out := make([]T, len(items))
	for i, e := range items {
		out[i] = f(e)
	}
	return out
}

func bindPtr[T any](v strictspec.Value, f func(strictspec.Value) T) *T {
	if v.IsNull() {
		return nil
	}
	t := f(v)
	return &t
}
