// Code generated by strictspec. DO NOT EDIT.
//
// strictspec generator: 0.1.0
// schema:              strictcode-vocabulary (format_version 1)
// regenerate:          strictspec gen --manifest strictspec.toml
//
// Released under the MIT license (unencumbered). This file is machine-generated;
// edit the schema and regenerate, never this file.
package vocabspec

import "github.com/smm-h/strictspec/go/strictspec"

// GeneratedBy is the strictspec release that produced this file. The runtime
// pairing guard hard-errors unless it matches the linked runtime exactly.
const GeneratedBy = "0.1.0"

// SchemaFormatVersion is the document format_version this validator accepts.
const SchemaFormatVersion = 1

// embeddedSchema carries the compiled schema (and its imported type-definition
// files and scalar manifest) so the validator is self-contained and does no IO.
var embeddedSchema = map[string]string{
	"vocabulary.schema.toml": `name = "strictcode-vocabulary"
meta_version = 1
format_version = 1
document_syntax = "toml"
role = "schema"
root = "Vocabulary"
targets = ["go"]
description = "Gates schema/vocabulary.toml: the universal node/row/capability vocabulary."

[types.Vocabulary]
type = "record"

[types.Vocabulary.fields.enums]
type = "array"
required = true
[types.Vocabulary.fields.enums.item]
type = "Enum"

[types.Vocabulary.fields.node_kinds]
type = "array"
required = true
[types.Vocabulary.fields.node_kinds.item]
type = "NodeKind"

[types.Vocabulary.fields.row_kinds]
type = "array"
required = true
[types.Vocabulary.fields.row_kinds.item]
type = "RowKind"

[types.Vocabulary.fields.capabilities]
type = "array"
required = true
[types.Vocabulary.fields.capabilities.item]
type = "Capability"

[types.Vocabulary.fields.layers]
type = "array"
required = true
[types.Vocabulary.fields.layers.item]
type = "Layer"

[[types.Vocabulary.constraints]]
form = "unique-by"
collection = "enums"
field = "id"
normalization = "none"

[[types.Vocabulary.constraints]]
form = "unique-by"
collection = "node_kinds"
field = "id"
normalization = "none"

[[types.Vocabulary.constraints]]
form = "unique-by"
collection = "row_kinds"
field = "id"
normalization = "none"

[[types.Vocabulary.constraints]]
form = "unique-by"
collection = "capabilities"
field = "id"
normalization = "none"

[[types.Vocabulary.constraints]]
form = "unique-by"
collection = "layers"
field = "id"
normalization = "none"

[[types.Vocabulary.constraints]]
form = "intra-document-references"
reference = "capabilities[].layer"
resolves_into = "layers[].id"
resolves_by = "equality"

[[types.Vocabulary.constraints]]
form = "intra-document-references"
reference = "row_kinds[].src_kinds[]"
resolves_into = "node_kinds[].id"
resolves_by = "equality"

[[types.Vocabulary.constraints]]
form = "intra-document-references"
reference = "row_kinds[].dst_kinds[]"
resolves_into = "node_kinds[].id"
resolves_by = "equality"

[types.Ident]
type = "string"
regex = "^[a-z][a-z0-9_-]*$"

[types.Maturity]
type = "enum"
values = ["stable", "speculative"]

[types.AttributeType]
type = "string"
regex = "^(string|boolean|integer|enum:[a-z][a-z0-9_]*)$"
description = "A scalar attribute type or a reference to a declared enum (enum:<id>)."

[types.Attribute]
type = "record"
[types.Attribute.fields.name]
type = "Ident"
required = true
[types.Attribute.fields.type]
type = "AttributeType"
required = true

[types.Enum]
type = "record"
[types.Enum.fields.id]
type = "Ident"
required = true
[types.Enum.fields.values]
type = "array"
required = true
min_len = 1
[types.Enum.fields.values.item]
type = "string"
non_empty = true

[types.NodeKind]
type = "record"
[types.NodeKind.fields.id]
type = "Ident"
required = true
[types.NodeKind.fields.maturity]
type = "Maturity"
required = true
[types.NodeKind.fields.description]
type = "string"
required = true
non_empty = true
[types.NodeKind.fields.attributes]
type = "array"
required = false
[types.NodeKind.fields.attributes.item]
type = "Attribute"

[types.RowKind]
type = "record"
[types.RowKind.fields.id]
type = "Ident"
required = true
[types.RowKind.fields.maturity]
type = "Maturity"
required = true
[types.RowKind.fields.description]
type = "string"
required = true
non_empty = true
[types.RowKind.fields.src_kinds]
type = "array"
required = true
min_len = 1
[types.RowKind.fields.src_kinds.item]
type = "Ident"
[types.RowKind.fields.dst_kinds]
type = "array"
required = true
min_len = 1
[types.RowKind.fields.dst_kinds.item]
type = "Ident"
[types.RowKind.fields.attributes]
type = "array"
required = false
[types.RowKind.fields.attributes.item]
type = "Attribute"

[types.Capability]
type = "record"
[types.Capability.fields.id]
type = "Ident"
required = true
[types.Capability.fields.layer]
type = "Ident"
required = true
[types.Capability.fields.description]
type = "string"
required = true
non_empty = true

[types.Layer]
type = "record"
[types.Layer.fields.id]
type = "Ident"
required = true
[types.Layer.fields.maturity]
type = "Maturity"
required = true
[types.Layer.fields.description]
type = "string"
required = true
non_empty = true
`,
}

const embeddedMainFile = "vocabulary.schema.toml"

var program *strictspec.Program

func init() {
	// Version pairing: generated code and runtime must be the same release.
	strictspec.RequireRuntimeVersion(GeneratedBy)
	p, err := strictspec.CompileEmbedded(embeddedSchema, embeddedMainFile)
	if err != nil {
		panic(err)
	}
	program = p
}

// ValidateBytes is the raw-bytes entry point: lossless parse of input in the
// given syntax ("json" | "toml" | "jsonl"), then validate. It returns the
// typed root value (nil when any diagnostic fired) and the ordered diagnostics.
func ValidateBytes(input []byte, syntax string) (*Vocabulary, []strictspec.Diagnostic) {
	res := program.Validate(input, syntax)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	v, err := strictspec.LoadValue(input, syntax)
	if err != nil {
		return nil, res.Diagnostics
	}
	return bindVocabulary(v), nil
}

// ValidateValue is the tagged-value entry point: validate an already-parsed
// tagged document value (from strictspec.LoadValue or a typed constructor).
func ValidateValue(v strictspec.Value) (*Vocabulary, []strictspec.Diagnostic) {
	res := program.ValidateValue(v)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	return bindVocabulary(v), nil
}

// ValidateBytesWithEvidence is ValidateBytes plus cross-document resolver
// evidence for the phase-2 constraint vocabulary.
func ValidateBytesWithEvidence(input []byte, syntax string, evidence map[string][]map[string]any) (*Vocabulary, []strictspec.Diagnostic) {
	res := program.ValidateWithEvidence(input, syntax, evidence)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	v, err := strictspec.LoadValue(input, syntax)
	if err != nil {
		return nil, res.Diagnostics
	}
	return bindVocabulary(v), nil
}

// Vocabulary is the frozen typed binding of the "Vocabulary" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type Vocabulary struct {
	Enums        []*Enum
	NodeKinds    []*NodeKind
	RowKinds     []*RowKind
	Capabilities []*Capability
	Layers       []*Layer
}

func bindVocabulary(v strictspec.Value) *Vocabulary {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &Vocabulary{}
	if fv, ok := v.Field("enums"); ok {
		out.Enums = bindSlice(fv, func(e strictspec.Value) *Enum { return bindEnum(e) })
	}
	if fv, ok := v.Field("node_kinds"); ok {
		out.NodeKinds = bindSlice(fv, func(e strictspec.Value) *NodeKind { return bindNodeKind(e) })
	}
	if fv, ok := v.Field("row_kinds"); ok {
		out.RowKinds = bindSlice(fv, func(e strictspec.Value) *RowKind { return bindRowKind(e) })
	}
	if fv, ok := v.Field("capabilities"); ok {
		out.Capabilities = bindSlice(fv, func(e strictspec.Value) *Capability { return bindCapability(e) })
	}
	if fv, ok := v.Field("layers"); ok {
		out.Layers = bindSlice(fv, func(e strictspec.Value) *Layer { return bindLayer(e) })
	}
	return out
}

// WithEnums returns a copy of Vocabulary with Enums set to the given value.
func (x *Vocabulary) WithEnums(v []*Enum) *Vocabulary {
	c := *x
	c.Enums = v
	return &c
}

// WithNodeKinds returns a copy of Vocabulary with NodeKinds set to the given value.
func (x *Vocabulary) WithNodeKinds(v []*NodeKind) *Vocabulary {
	c := *x
	c.NodeKinds = v
	return &c
}

// WithRowKinds returns a copy of Vocabulary with RowKinds set to the given value.
func (x *Vocabulary) WithRowKinds(v []*RowKind) *Vocabulary {
	c := *x
	c.RowKinds = v
	return &c
}

// WithCapabilities returns a copy of Vocabulary with Capabilities set to the given value.
func (x *Vocabulary) WithCapabilities(v []*Capability) *Vocabulary {
	c := *x
	c.Capabilities = v
	return &c
}

// WithLayers returns a copy of Vocabulary with Layers set to the given value.
func (x *Vocabulary) WithLayers(v []*Layer) *Vocabulary {
	c := *x
	c.Layers = v
	return &c
}

// Attribute is the frozen typed binding of the "Attribute" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type Attribute struct {
	Name string
	Type string
}

func bindAttribute(v strictspec.Value) *Attribute {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &Attribute{}
	if fv, ok := v.Field("name"); ok {
		out.Name = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("type"); ok {
		out.Type = func() string { r, _ := fv.AsString(); return r }()
	}
	return out
}

// WithName returns a copy of Attribute with Name set to the given value.
func (x *Attribute) WithName(v string) *Attribute {
	c := *x
	c.Name = v
	return &c
}

// WithType returns a copy of Attribute with Type set to the given value.
func (x *Attribute) WithType(v string) *Attribute {
	c := *x
	c.Type = v
	return &c
}

// Enum is the frozen typed binding of the "Enum" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type Enum struct {
	Id     string
	Values []string
}

func bindEnum(v strictspec.Value) *Enum {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &Enum{}
	if fv, ok := v.Field("id"); ok {
		out.Id = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("values"); ok {
		out.Values = bindSlice(fv, func(e strictspec.Value) string { return func() string { r, _ := e.AsString(); return r }() })
	}
	return out
}

// WithId returns a copy of Enum with Id set to the given value.
func (x *Enum) WithId(v string) *Enum {
	c := *x
	c.Id = v
	return &c
}

// WithValues returns a copy of Enum with Values set to the given value.
func (x *Enum) WithValues(v []string) *Enum {
	c := *x
	c.Values = v
	return &c
}

// NodeKind is the frozen typed binding of the "NodeKind" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type NodeKind struct {
	Id          string
	Maturity    string
	Description string
	Attributes  []*Attribute
}

func bindNodeKind(v strictspec.Value) *NodeKind {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &NodeKind{}
	if fv, ok := v.Field("id"); ok {
		out.Id = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("maturity"); ok {
		out.Maturity = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("description"); ok {
		out.Description = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("attributes"); ok {
		out.Attributes = bindSlice(fv, func(e strictspec.Value) *Attribute { return bindAttribute(e) })
	}
	return out
}

// WithId returns a copy of NodeKind with Id set to the given value.
func (x *NodeKind) WithId(v string) *NodeKind {
	c := *x
	c.Id = v
	return &c
}

// WithMaturity returns a copy of NodeKind with Maturity set to the given value.
func (x *NodeKind) WithMaturity(v string) *NodeKind {
	c := *x
	c.Maturity = v
	return &c
}

// WithDescription returns a copy of NodeKind with Description set to the given value.
func (x *NodeKind) WithDescription(v string) *NodeKind {
	c := *x
	c.Description = v
	return &c
}

// WithAttributes returns a copy of NodeKind with Attributes set to the given value.
func (x *NodeKind) WithAttributes(v []*Attribute) *NodeKind {
	c := *x
	c.Attributes = v
	return &c
}

// RowKind is the frozen typed binding of the "RowKind" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type RowKind struct {
	Id          string
	Maturity    string
	Description string
	SrcKinds    []string
	DstKinds    []string
	Attributes  []*Attribute
}

func bindRowKind(v strictspec.Value) *RowKind {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &RowKind{}
	if fv, ok := v.Field("id"); ok {
		out.Id = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("maturity"); ok {
		out.Maturity = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("description"); ok {
		out.Description = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("src_kinds"); ok {
		out.SrcKinds = bindSlice(fv, func(e strictspec.Value) string { return func() string { r, _ := e.AsString(); return r }() })
	}
	if fv, ok := v.Field("dst_kinds"); ok {
		out.DstKinds = bindSlice(fv, func(e strictspec.Value) string { return func() string { r, _ := e.AsString(); return r }() })
	}
	if fv, ok := v.Field("attributes"); ok {
		out.Attributes = bindSlice(fv, func(e strictspec.Value) *Attribute { return bindAttribute(e) })
	}
	return out
}

// WithId returns a copy of RowKind with Id set to the given value.
func (x *RowKind) WithId(v string) *RowKind {
	c := *x
	c.Id = v
	return &c
}

// WithMaturity returns a copy of RowKind with Maturity set to the given value.
func (x *RowKind) WithMaturity(v string) *RowKind {
	c := *x
	c.Maturity = v
	return &c
}

// WithDescription returns a copy of RowKind with Description set to the given value.
func (x *RowKind) WithDescription(v string) *RowKind {
	c := *x
	c.Description = v
	return &c
}

// WithSrcKinds returns a copy of RowKind with SrcKinds set to the given value.
func (x *RowKind) WithSrcKinds(v []string) *RowKind {
	c := *x
	c.SrcKinds = v
	return &c
}

// WithDstKinds returns a copy of RowKind with DstKinds set to the given value.
func (x *RowKind) WithDstKinds(v []string) *RowKind {
	c := *x
	c.DstKinds = v
	return &c
}

// WithAttributes returns a copy of RowKind with Attributes set to the given value.
func (x *RowKind) WithAttributes(v []*Attribute) *RowKind {
	c := *x
	c.Attributes = v
	return &c
}

// Capability is the frozen typed binding of the "Capability" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type Capability struct {
	Id          string
	Layer       string
	Description string
}

func bindCapability(v strictspec.Value) *Capability {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &Capability{}
	if fv, ok := v.Field("id"); ok {
		out.Id = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("layer"); ok {
		out.Layer = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("description"); ok {
		out.Description = func() string { r, _ := fv.AsString(); return r }()
	}
	return out
}

// WithId returns a copy of Capability with Id set to the given value.
func (x *Capability) WithId(v string) *Capability {
	c := *x
	c.Id = v
	return &c
}

// WithLayer returns a copy of Capability with Layer set to the given value.
func (x *Capability) WithLayer(v string) *Capability {
	c := *x
	c.Layer = v
	return &c
}

// WithDescription returns a copy of Capability with Description set to the given value.
func (x *Capability) WithDescription(v string) *Capability {
	c := *x
	c.Description = v
	return &c
}

// Layer is the frozen typed binding of the "Layer" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type Layer struct {
	Id          string
	Maturity    string
	Description string
}

func bindLayer(v strictspec.Value) *Layer {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &Layer{}
	if fv, ok := v.Field("id"); ok {
		out.Id = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("maturity"); ok {
		out.Maturity = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("description"); ok {
		out.Description = func() string { r, _ := fv.AsString(); return r }()
	}
	return out
}

// WithId returns a copy of Layer with Id set to the given value.
func (x *Layer) WithId(v string) *Layer {
	c := *x
	c.Id = v
	return &c
}

// WithMaturity returns a copy of Layer with Maturity set to the given value.
func (x *Layer) WithMaturity(v string) *Layer {
	c := *x
	c.Maturity = v
	return &c
}

// WithDescription returns a copy of Layer with Description set to the given value.
func (x *Layer) WithDescription(v string) *Layer {
	c := *x
	c.Description = v
	return &c
}

func bindSlice[T any](v strictspec.Value, f func(strictspec.Value) T) []T {
	items := v.Items()
	out := make([]T, len(items))
	for i, e := range items {
		out[i] = f(e)
	}
	return out
}

func bindPtr[T any](v strictspec.Value, f func(strictspec.Value) T) *T {
	if v.IsNull() {
		return nil
	}
	t := f(v)
	return &t
}
