// Code generated by strictspec. DO NOT EDIT.
//
// strictspec generator: 0.4.0
// schema:              strictcode-registry (format_version 2)
// regenerate:          strictspec gen --manifest strictspec.toml
//
// Released under the MIT license (unencumbered). This file is machine-generated;
// edit the schema and regenerate, never this file.
package registryspec

import "github.com/stricttools/strictspec/go/strictspec"

// GENERATED_BY is the strictspec release that produced this file. It is
// INFORMATIONAL: pairing is on GENERATED_CODE_FORMAT below, so a later release
// of the runtime reads this file unchanged, and no tool may derive a dependency
// floor from this string.
const GENERATED_BY = "0.4.0"

// GENERATED_CODE_FORMAT is the shape of generated code this file was written
// to. The runtime pairing guard hard-errors unless this format is one the
// linked runtime reads; the remedy is regeneration.
const GENERATED_CODE_FORMAT = 2

// SCHEMA_FORMAT_VERSION is the document format_version this validator accepts.
const SCHEMA_FORMAT_VERSION = 2

// embeddedSchema carries the compiled schema (and its imported type-definition
// files and scalar manifest) so the validator is self-contained and does no IO.
var embeddedSchema = map[string]string{
	"registry.schema.toml": `name = "strictcode-registry"
meta_version = 1
format_version = 2
document_syntax = "json"
role = "schema"
root = "Registry"
targets = ["go"]
description = "Validates schema/registry.json: the committed rule-registry dump (rules, groups, and retired-rule records; see the rules page in stricttools/docs/rules.md). The release diff classifies version bumps from this artifact, and the docs site renders its rule and support-matrix tables from it. Capability enums are sourced from schema/vocabulary.toml (strictspec decision 32)."

[types.Registry]
type = "record"

[types.Registry.fields.languages]
type = "array"
required = true
min_len = 1
description = "The languages of the support matrix, in column order, with the display names from their profiles."
[types.Registry.fields.languages.item]
type = "LanguageDecl"

[types.Registry.fields.rules]
type = "array"
required = true
min_len = 1
[types.Registry.fields.rules.item]
type = "RuleDecl"

[types.Registry.fields.groups]
type = "map"
required = true
key_pattern = "^[a-z][a-z0-9-]*$"
order = "incidental"
[types.Registry.fields.groups.value]
type = "array"
[types.Registry.fields.groups.value.item]
type = "RuleId"

[types.Registry.fields.tombstones]
type = "array"
required = true
[types.Registry.fields.tombstones.item]
type = "TombstoneDecl"

[[types.Registry.constraints]]
form = "unique-by"
collection = "rules"
field = "id"
normalization = "none"

[[types.Registry.constraints]]
form = "unique-by"
collection = "tombstones"
field = "id"
normalization = "none"

[types.LanguageDecl]
type = "record"

[types.LanguageDecl.fields.id]
type = "enum"
required = true
values = ["py", "go", "ts"]

[types.LanguageDecl.fields.display_name]
type = "string"
required = true
non_empty = true

[types.RuleId]
type = "string"
regex = "^[a-z][a-z0-9]*(-[a-z0-9]+)*$"
description = "A minted rule identifier: flat, lowercase, hyphenated, encoding nothing."

[types.CapabilityId]
type = "enum"
description = "Sourced from the vocabulary (capabilities)."
[types.CapabilityId.source]
document = "schema/vocabulary.toml"
selector = "capabilities[].id"
baked = [
  "module-enumeration",
  "import-extraction",
  "resolve-imports-internal",
  "resolve-imports-modules",
  "import-attr-guarded",
  "import-attr-type-checking",
  "test-context-classification",
  "entry-point-discovery",
  "declared-dependency-extraction",
  "export-extraction",
  "callable-extraction",
  "type-extraction",
  "call-resolution-syntactic",
  "call-resolution-type-informed",
  "conformance-declared",
  "conformance-derived",
  "instantiation-extraction",
  "reference-extraction",
  "decoration-extraction",
  "unreachable-statement-analysis",
  "endpoint-discovery",
  "db-entity-discovery",
]

[types.RuleDecl]
type = "record"

[types.RuleDecl.fields.id]
type = "RuleId"
required = true

[types.RuleDecl.fields.severity]
type = "enum"
required = true
values = ["error", "warning"]

[types.RuleDecl.fields.description]
type = "string"
required = true
non_empty = true

[types.RuleDecl.fields.requires]
type = "array"
required = true
[types.RuleDecl.fields.requires.item]
type = "CapabilityId"

[types.RuleDecl.fields.uses]
type = "array"
required = true
[types.RuleDecl.fields.uses.item]
type = "CapabilityId"

[types.RuleDecl.fields.groups]
type = "array"
required = true
[types.RuleDecl.fields.groups.item]
type = "string"
regex = "^[a-z][a-z0-9-]*$"

[types.RuleDecl.fields.suppression]
type = "enum"
required = true
values = ["none", "path", "project-dep", "member-set", "member"]
description = "The rule's suppression target shape (see stricttools/docs/config.md)."

[types.RuleDecl.fields.fix_tier]
type = "integer"
required = true
min = 1
max = 3

[types.RuleDecl.fields.planned_fixes]
type = "array"
required = true
[types.RuleDecl.fields.planned_fixes.item]
type = "PlannedFixDecl"

[types.RuleDecl.fields.not_applicable]
type = "map"
required = true
key_pattern = "^(py|go|ts)$"
order = "incidental"
[types.RuleDecl.fields.not_applicable.value]
type = "string"
non_empty = true

[types.RuleDecl.fields.language_independent]
type = "boolean"
required = true
description = "True when the rule engages no language capability (it is evaluated against config, disk, and the registry), so it applies to every project and has no per-language support cells."

[types.RuleDecl.fields.support]
type = "map"
required = true
key_pattern = "^(py|go|ts)$"
order = "incidental"
description = "The computed support-matrix cell per language, from the requires/uses capability model, the language profiles, and the rule's not_applicable overrides. Empty if and only if language_independent is true."
[types.RuleDecl.fields.support.value]
type = "SupportCell"

[types.SupportCell]
type = "record"

[types.SupportCell.fields.status]
type = "enum"
required = true
values = ["supported", "planned", "n/a"]

[types.SupportCell.fields.reason]
type = "string"
required = false
non_empty = true
description = "Why the rule is not applicable in this language. Present if and only if status is n/a."

[[types.SupportCell.constraints]]
form = "conditional-required"
field = "reason"
when = { field = "status", predicate = "equals", value = "n/a" }

[[types.SupportCell.constraints]]
form = "forbidden-when"
field = "reason"
when = { field = "status", predicate = "in", values = ["supported", "planned"] }

[types.PlannedFixDecl]
type = "record"

[types.PlannedFixDecl.fields.tier]
type = "integer"
required = true
min = 1
max = 2

[types.PlannedFixDecl.fields.description]
type = "string"
required = true
non_empty = true

[types.TombstoneDecl]
type = "record"

[types.TombstoneDecl.fields.id]
type = "RuleId"
required = true

[types.TombstoneDecl.fields.retired_in]
type = "string"
required = true
non_empty = true

[types.TombstoneDecl.fields.reason]
type = "string"
required = true
non_empty = true

[types.TombstoneDecl.fields.replaced_by]
type = "array"
required = true
[types.TombstoneDecl.fields.replaced_by.item]
type = "RuleId"

[types.TombstoneDecl.fields.migration]
type = "string"
required = true
non_empty = true
`,
}

const embeddedMainFile = "registry.schema.toml"

var program *strictspec.Program

func init() {
	// Pairing: this file's generated-code format must be one the runtime reads.
	strictspec.RequireGeneratedCodeFormat(GENERATED_CODE_FORMAT, GENERATED_BY)
	p, err := strictspec.CompileEmbedded(embeddedSchema, embeddedMainFile)
	if err != nil {
		panic(err)
	}
	program = p
}

// ValidateBytes is the raw-bytes entry point: lossless parse of input in the
// given syntax ("json" | "toml" | "jsonl"), then validate. It returns the
// typed root value (nil when any diagnostic fired) and the ordered diagnostics.
func ValidateBytes(input []byte, syntax string) (*Registry, []strictspec.Diagnostic) {
	res := program.Validate(input, syntax)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	v, err := strictspec.LoadValue(input, syntax)
	if err != nil {
		return nil, res.Diagnostics
	}
	return bindRegistry(v), nil
}

// ValidateValue is the tagged-value entry point: validate an already-parsed
// tagged document value (from strictspec.LoadValue or a typed constructor).
func ValidateValue(v strictspec.Value) (*Registry, []strictspec.Diagnostic) {
	res := program.ValidateValue(v)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	return bindRegistry(v), nil
}

// ValidateBytesWithEvidence is ValidateBytes plus cross-document resolver
// evidence for the constraint vocabulary.
func ValidateBytesWithEvidence(input []byte, syntax string, evidence map[string][]map[string]any) (*Registry, []strictspec.Diagnostic) {
	res := program.ValidateWithEvidence(input, syntax, evidence)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	v, err := strictspec.LoadValue(input, syntax)
	if err != nil {
		return nil, res.Diagnostics
	}
	return bindRegistry(v), nil
}

// Registry is the frozen typed binding of the "Registry" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type Registry struct {
	Languages  []*LanguageDecl
	Rules      []*RuleDecl
	Groups     strictspec.Value
	Tombstones []*TombstoneDecl
}

func bindRegistry(v strictspec.Value) *Registry {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &Registry{}
	if fv, ok := v.Field("languages"); ok {
		out.Languages = bindSlice(fv, func(e strictspec.Value) *LanguageDecl { return bindLanguageDecl(e) })
	}
	if fv, ok := v.Field("rules"); ok {
		out.Rules = bindSlice(fv, func(e strictspec.Value) *RuleDecl { return bindRuleDecl(e) })
	}
	if fv, ok := v.Field("groups"); ok {
		out.Groups = fv
	}
	if fv, ok := v.Field("tombstones"); ok {
		out.Tombstones = bindSlice(fv, func(e strictspec.Value) *TombstoneDecl { return bindTombstoneDecl(e) })
	}
	return out
}

// WithLanguages returns a copy of Registry with Languages set to the given value.
func (x *Registry) WithLanguages(v []*LanguageDecl) *Registry {
	c := *x
	c.Languages = v
	return &c
}

// WithRules returns a copy of Registry with Rules set to the given value.
func (x *Registry) WithRules(v []*RuleDecl) *Registry {
	c := *x
	c.Rules = v
	return &c
}

// WithGroups returns a copy of Registry with Groups set to the given value.
func (x *Registry) WithGroups(v strictspec.Value) *Registry {
	c := *x
	c.Groups = v
	return &c
}

// WithTombstones returns a copy of Registry with Tombstones set to the given value.
func (x *Registry) WithTombstones(v []*TombstoneDecl) *Registry {
	c := *x
	c.Tombstones = v
	return &c
}

// LanguageDecl is the frozen typed binding of the "LanguageDecl" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type LanguageDecl struct {
	Id          string
	DisplayName string
}

func bindLanguageDecl(v strictspec.Value) *LanguageDecl {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &LanguageDecl{}
	if fv, ok := v.Field("id"); ok {
		out.Id = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("display_name"); ok {
		out.DisplayName = func() string { r, _ := fv.AsString(); return r }()
	}
	return out
}

// WithId returns a copy of LanguageDecl with Id set to the given value.
func (x *LanguageDecl) WithId(v string) *LanguageDecl {
	c := *x
	c.Id = v
	return &c
}

// WithDisplayName returns a copy of LanguageDecl with DisplayName set to the given value.
func (x *LanguageDecl) WithDisplayName(v string) *LanguageDecl {
	c := *x
	c.DisplayName = v
	return &c
}

// RuleDecl is the frozen typed binding of the "RuleDecl" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type RuleDecl struct {
	Id                  string
	Severity            string
	Description         string
	Requires            []string
	Uses                []string
	Groups              []string
	Suppression         string
	FixTier             int64
	PlannedFixes        []*PlannedFixDecl
	NotApplicable       strictspec.Value
	LanguageIndependent bool
	Support             strictspec.Value
}

func bindRuleDecl(v strictspec.Value) *RuleDecl {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &RuleDecl{}
	if fv, ok := v.Field("id"); ok {
		out.Id = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("severity"); ok {
		out.Severity = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("description"); ok {
		out.Description = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("requires"); ok {
		out.Requires = bindSlice(fv, func(e strictspec.Value) string { return func() string { r, _ := e.AsString(); return r }() })
	}
	if fv, ok := v.Field("uses"); ok {
		out.Uses = bindSlice(fv, func(e strictspec.Value) string { return func() string { r, _ := e.AsString(); return r }() })
	}
	if fv, ok := v.Field("groups"); ok {
		out.Groups = bindSlice(fv, func(e strictspec.Value) string { return func() string { r, _ := e.AsString(); return r }() })
	}
	if fv, ok := v.Field("suppression"); ok {
		out.Suppression = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("fix_tier"); ok {
		out.FixTier = func() int64 { r, _ := fv.Int(); return r }()
	}
	if fv, ok := v.Field("planned_fixes"); ok {
		out.PlannedFixes = bindSlice(fv, func(e strictspec.Value) *PlannedFixDecl { return bindPlannedFixDecl(e) })
	}
	if fv, ok := v.Field("not_applicable"); ok {
		out.NotApplicable = fv
	}
	if fv, ok := v.Field("language_independent"); ok {
		out.LanguageIndependent = func() bool { r, _ := fv.Bool(); return r }()
	}
	if fv, ok := v.Field("support"); ok {
		out.Support = fv
	}
	return out
}

// WithId returns a copy of RuleDecl with Id set to the given value.
func (x *RuleDecl) WithId(v string) *RuleDecl {
	c := *x
	c.Id = v
	return &c
}

// WithSeverity returns a copy of RuleDecl with Severity set to the given value.
func (x *RuleDecl) WithSeverity(v string) *RuleDecl {
	c := *x
	c.Severity = v
	return &c
}

// WithDescription returns a copy of RuleDecl with Description set to the given value.
func (x *RuleDecl) WithDescription(v string) *RuleDecl {
	c := *x
	c.Description = v
	return &c
}

// WithRequires returns a copy of RuleDecl with Requires set to the given value.
func (x *RuleDecl) WithRequires(v []string) *RuleDecl {
	c := *x
	c.Requires = v
	return &c
}

// WithUses returns a copy of RuleDecl with Uses set to the given value.
func (x *RuleDecl) WithUses(v []string) *RuleDecl {
	c := *x
	c.Uses = v
	return &c
}

// WithGroups returns a copy of RuleDecl with Groups set to the given value.
func (x *RuleDecl) WithGroups(v []string) *RuleDecl {
	c := *x
	c.Groups = v
	return &c
}

// WithSuppression returns a copy of RuleDecl with Suppression set to the given value.
func (x *RuleDecl) WithSuppression(v string) *RuleDecl {
	c := *x
	c.Suppression = v
	return &c
}

// WithFixTier returns a copy of RuleDecl with FixTier set to the given value.
func (x *RuleDecl) WithFixTier(v int64) *RuleDecl {
	c := *x
	c.FixTier = v
	return &c
}

// WithPlannedFixes returns a copy of RuleDecl with PlannedFixes set to the given value.
func (x *RuleDecl) WithPlannedFixes(v []*PlannedFixDecl) *RuleDecl {
	c := *x
	c.PlannedFixes = v
	return &c
}

// WithNotApplicable returns a copy of RuleDecl with NotApplicable set to the given value.
func (x *RuleDecl) WithNotApplicable(v strictspec.Value) *RuleDecl {
	c := *x
	c.NotApplicable = v
	return &c
}

// WithLanguageIndependent returns a copy of RuleDecl with LanguageIndependent set to the given value.
func (x *RuleDecl) WithLanguageIndependent(v bool) *RuleDecl {
	c := *x
	c.LanguageIndependent = v
	return &c
}

// WithSupport returns a copy of RuleDecl with Support set to the given value.
func (x *RuleDecl) WithSupport(v strictspec.Value) *RuleDecl {
	c := *x
	c.Support = v
	return &c
}

// SupportCell is the frozen typed binding of the "SupportCell" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type SupportCell struct {
	Status string
	Reason string
}

func bindSupportCell(v strictspec.Value) *SupportCell {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &SupportCell{}
	if fv, ok := v.Field("status"); ok {
		out.Status = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("reason"); ok {
		out.Reason = func() string { r, _ := fv.AsString(); return r }()
	}
	return out
}

// WithStatus returns a copy of SupportCell with Status set to the given value.
func (x *SupportCell) WithStatus(v string) *SupportCell {
	c := *x
	c.Status = v
	return &c
}

// WithReason returns a copy of SupportCell with Reason set to the given value.
func (x *SupportCell) WithReason(v string) *SupportCell {
	c := *x
	c.Reason = v
	return &c
}

// PlannedFixDecl is the frozen typed binding of the "PlannedFixDecl" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type PlannedFixDecl struct {
	Tier        int64
	Description string
}

func bindPlannedFixDecl(v strictspec.Value) *PlannedFixDecl {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &PlannedFixDecl{}
	if fv, ok := v.Field("tier"); ok {
		out.Tier = func() int64 { r, _ := fv.Int(); return r }()
	}
	if fv, ok := v.Field("description"); ok {
		out.Description = func() string { r, _ := fv.AsString(); return r }()
	}
	return out
}

// WithTier returns a copy of PlannedFixDecl with Tier set to the given value.
func (x *PlannedFixDecl) WithTier(v int64) *PlannedFixDecl {
	c := *x
	c.Tier = v
	return &c
}

// WithDescription returns a copy of PlannedFixDecl with Description set to the given value.
func (x *PlannedFixDecl) WithDescription(v string) *PlannedFixDecl {
	c := *x
	c.Description = v
	return &c
}

// TombstoneDecl is the frozen typed binding of the "TombstoneDecl" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type TombstoneDecl struct {
	Id         string
	RetiredIn  string
	Reason     string
	ReplacedBy []string
	Migration  string
}

func bindTombstoneDecl(v strictspec.Value) *TombstoneDecl {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &TombstoneDecl{}
	if fv, ok := v.Field("id"); ok {
		out.Id = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("retired_in"); ok {
		out.RetiredIn = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("reason"); ok {
		out.Reason = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("replaced_by"); ok {
		out.ReplacedBy = bindSlice(fv, func(e strictspec.Value) string { return func() string { r, _ := e.AsString(); return r }() })
	}
	if fv, ok := v.Field("migration"); ok {
		out.Migration = func() string { r, _ := fv.AsString(); return r }()
	}
	return out
}

// WithId returns a copy of TombstoneDecl with Id set to the given value.
func (x *TombstoneDecl) WithId(v string) *TombstoneDecl {
	c := *x
	c.Id = v
	return &c
}

// WithRetiredIn returns a copy of TombstoneDecl with RetiredIn set to the given value.
func (x *TombstoneDecl) WithRetiredIn(v string) *TombstoneDecl {
	c := *x
	c.RetiredIn = v
	return &c
}

// WithReason returns a copy of TombstoneDecl with Reason set to the given value.
func (x *TombstoneDecl) WithReason(v string) *TombstoneDecl {
	c := *x
	c.Reason = v
	return &c
}

// WithReplacedBy returns a copy of TombstoneDecl with ReplacedBy set to the given value.
func (x *TombstoneDecl) WithReplacedBy(v []string) *TombstoneDecl {
	c := *x
	c.ReplacedBy = v
	return &c
}

// WithMigration returns a copy of TombstoneDecl with Migration set to the given value.
func (x *TombstoneDecl) WithMigration(v string) *TombstoneDecl {
	c := *x
	c.Migration = v
	return &c
}

func bindSlice[T any](v strictspec.Value, f func(strictspec.Value) T) []T {
	items := v.Items()
	out := make([]T, len(items))
	for i, e := range items {
		out[i] = f(e)
	}
	return out
}

func bindPtr[T any](v strictspec.Value, f func(strictspec.Value) T) *T {
	if v.IsNull() {
		return nil
	}
	t := f(v)
	return &t
}
