// Package registrydump renders the committed registry artifacts:
// REGISTRY.json (the machine-readable rule registry the CI release diff
// classifies bumps from) and docs/MATRIX.md (the language x feature support
// matrix generated from the registry and the language profiles).
//
// Both renderings are deterministic. RegistryJSON self-validates its output
// through the strictspec-generated reader before returning — an invalid dump
// is a hard error, never a written artifact.
package registrydump

import (
	"encoding/json"
	"fmt"
	"strings"

	"github.com/smm-h/strictcode/internal/rules"
	"github.com/smm-h/strictcode/internal/spec/registryspec"
	"github.com/smm-h/strictcode/internal/vocab"
)

// FormatVersion is the registry dump's document format_version, checked
// exactly by the strictspec schema (schema/strictspec/registry.schema.toml).
const FormatVersion = 1

type ruleJSON struct {
	ID            string            `json:"id"`
	Severity      string            `json:"severity"`
	Description   string            `json:"description"`
	Requires      []string          `json:"requires"`
	Uses          []string          `json:"uses"`
	Groups        []string          `json:"groups"`
	Suppression   string            `json:"suppression"`
	FixTier       int               `json:"fix_tier"`
	PlannedFixes  []plannedFixJSON  `json:"planned_fixes"`
	NotApplicable map[string]string `json:"not_applicable"`
}

type plannedFixJSON struct {
	Tier        int    `json:"tier"`
	Description string `json:"description"`
}

type tombstoneJSON struct {
	ID         string   `json:"id"`
	RetiredIn  string   `json:"retired_in"`
	Reason     string   `json:"reason"`
	ReplacedBy []string `json:"replaced_by"`
	Migration  string   `json:"migration"`
}

type registryJSON struct {
	FormatVersion int                 `json:"format_version"`
	Rules         []ruleJSON          `json:"rules"`
	Groups        map[string][]string `json:"groups"`
	Tombstones    []tombstoneJSON     `json:"tombstones"`
}

// RegistryJSON renders the registry as deterministic, indented JSON with a
// trailing newline, self-validated against the strictspec registry schema.
func RegistryJSON() ([]byte, error) {
	doc := registryJSON{
		FormatVersion: FormatVersion,
		Rules:         make([]ruleJSON, 0, len(rules.Rules)),
		Groups:        map[string][]string{},
		Tombstones:    make([]tombstoneJSON, 0, len(rules.Tombstones)),
	}
	for _, r := range rules.Rules {
		rj := ruleJSON{
			ID:            r.ID,
			Severity:      string(r.Severity),
			Description:   r.Description,
			Requires:      capStrings(r.Requires),
			Uses:          capStrings(r.Uses),
			Groups:        emptyNotNil(r.Groups),
			Suppression:   string(r.Suppression),
			FixTier:       int(r.FixTier),
			PlannedFixes:  make([]plannedFixJSON, 0, len(r.PlannedFixes)),
			NotApplicable: map[string]string{},
		}
		for _, pf := range r.PlannedFixes {
			rj.PlannedFixes = append(rj.PlannedFixes, plannedFixJSON{Tier: int(pf.Tier), Description: pf.Description})
		}
		for lang, reason := range r.NotApplicable {
			rj.NotApplicable[string(lang)] = reason
		}
		doc.Rules = append(doc.Rules, rj)
	}
	for name, members := range rules.Groups {
		doc.Groups[name] = emptyNotNil(members)
	}
	for _, t := range rules.Tombstones {
		doc.Tombstones = append(doc.Tombstones, tombstoneJSON{
			ID: t.ID, RetiredIn: t.RetiredIn, Reason: t.Reason,
			ReplacedBy: emptyNotNil(t.ReplacedBy), Migration: t.Migration,
		})
	}

	out, err := json.MarshalIndent(doc, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("registrydump: %w", err)
	}
	out = append(out, '\n')

	// Self-check: the artifact must validate against its own schema.
	if _, diags := registryspec.ValidateBytes(out, "json"); len(diags) != 0 {
		return nil, fmt.Errorf("registrydump: generated REGISTRY.json fails its schema: %v", diags)
	}
	return out, nil
}

func capStrings(caps []vocab.Capability) []string {
	out := make([]string, 0, len(caps))
	for _, c := range caps {
		out = append(out, string(c))
	}
	return out
}

func emptyNotNil(in []string) []string {
	if in == nil {
		return []string{}
	}
	return in
}

// MatrixMarkdown renders docs/MATRIX.md: the language x feature support
// matrix, computed from the rule registry (requires/uses model plus per-rule
// not_applicable overrides) and the capability statuses in the language
// profiles.
func MatrixMarkdown() []byte {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	langHeaders := make([]string, 0, len(vocab.Langs))
	for _, lang := range vocab.Langs {
		langHeaders = append(langHeaders, vocab.Profiles[lang].DisplayName)
	}

	w("<!-- Generated by `strictcode matrix gen` from the rule registry and schema/profiles/. Do not edit. -->\n\n")
	w("# strictcode support matrix\n\n")
	w("Cells: `supported` (extractor landed with tests), `planned` (designed, not\n")
	w("yet implemented), `n/a` (meaningless in that ecosystem — the reason is the\n")
	w("cell). Rule cells are computed from the registry's requires/uses capability\n")
	w("model and per-rule overrides; capability cells come from the language\n")
	w("profiles.\n\n")

	// --- Rules table ---
	w("## Rules\n\n")
	w("| Rule | %s |\n", strings.Join(langHeaders, " | "))
	w("|---|%s\n", strings.Repeat("---|", len(langHeaders)))
	var langIndependent []rules.Rule
	for _, r := range rules.Rules {
		if r.LanguageIndependent() {
			langIndependent = append(langIndependent, r)
			continue
		}
		cells := make([]string, 0, len(vocab.Langs))
		for _, lang := range vocab.Langs {
			cells = append(cells, renderCell(rules.MatrixCell(r, lang)))
		}
		w("| `%s` | %s |\n", r.ID, strings.Join(cells, " | "))
	}
	if len(langIndependent) > 0 {
		w("\n### Language-independent rules\n\n")
		w("These rules engage no language capabilities; they apply to every project\nregardless of language.\n\n")
		for _, r := range langIndependent {
			w("- `%s` — %s\n", r.ID, r.Description)
		}
	}

	// --- Capabilities table ---
	w("\n## Capabilities\n\n")
	w("| Capability | Layer | %s |\n", strings.Join(langHeaders, " | "))
	w("|---|---|%s\n", strings.Repeat("---|", len(langHeaders)))
	for _, cap := range vocab.Capabilities {
		cells := make([]string, 0, len(vocab.Langs))
		for _, lang := range vocab.Langs {
			pc := vocab.Profiles[lang].Capabilities[cap]
			switch pc.Status {
			case vocab.StatusNotApplicable:
				cells = append(cells, "n/a — "+pc.Reason)
			default:
				cells = append(cells, string(pc.Status))
			}
		}
		w("| `%s` | %s | %s |\n", cap, vocab.CapabilityLayer[cap], strings.Join(cells, " | "))
	}
	return []byte(b.String())
}

func renderCell(c rules.Cell) string {
	if c.Status == rules.CellNotApplicable {
		return "n/a — " + c.Reason
	}
	return string(c.Status)
}
