// Code generated by strictspec. DO NOT EDIT.
//
// strictspec generator: 0.1.0
// schema:              strictcode-findings (format_version 1)
// regenerate:          strictspec gen --manifest strictspec.toml
//
// Released under the MIT license (unencumbered). This file is machine-generated;
// edit the schema and regenerate, never this file.
package findingsspec

import "github.com/smm-h/strictspec/go/strictspec"

// GeneratedBy is the strictspec release that produced this file. The runtime
// pairing guard hard-errors unless it matches the linked runtime exactly.
const GeneratedBy = "0.1.0"

// SchemaFormatVersion is the document format_version this validator accepts.
const SchemaFormatVersion = 1

// embeddedSchema carries the compiled schema (and its imported type-definition
// files and scalar manifest) so the validator is self-contained and does no IO.
var embeddedSchema = map[string]string{
	"findings.schema.toml": `name = "strictcode-findings"
meta_version = 1
format_version = 1
document_syntax = "json"
role = "schema"
root = "Findings"
targets = ["go"]
description = "The strictcode JSON output format. Minimal v1 shape, designed for iteration. Vocabulary content versioning physically lives here: kind enums are SOURCED from schema/vocabulary.toml, so vocabulary changes are format changes of this schema (strictspec decision 32)."

[types.Findings]
type = "record"

[types.Findings.fields.strictcode_version]
type = "string"
required = true
non_empty = true

[types.Findings.fields.workspace_root]
type = "string"
required = true
non_empty = true

[types.Findings.fields.findings]
type = "array"
required = true
[types.Findings.fields.findings.item]
type = "Finding"

[types.Finding]
type = "record"

[types.Finding.fields.rule]
type = "string"
required = true
regex = "^[a-z][a-z0-9-]*$"
description = "Stable rule identifier (lowercase, hyphenated) — the same identifiers rlsbl external-check configs reference."

[types.Finding.fields.severity]
type = "enum"
required = true
values = ["error", "warning"]

[types.Finding.fields.message]
type = "string"
required = true
non_empty = true

[types.Finding.fields.target]
type = "Target"
required = true

[types.Finding.fields.fix]
type = "Fix"
required = false

[types.Target]
type = "record"

[types.Target.fields.id]
type = "string"
required = true
non_empty = true
description = "Serialized qualified node ID (SPEC.md section 2)."

[types.Target.fields.kind]
type = "enum"
required = true
description = "Sourced from the vocabulary (node kinds)."
[types.Target.fields.kind.source]
document = "schema/vocabulary.toml"
selector = "node_kinds[].id"
baked = [
  "workspace_member",
  "module",
  "entry_point",
  "function",
  "closure",
  "type",
  "type_param",
  "variable",
  "endpoint",
  "db_entity",
]

[types.Target.fields.file]
type = "string"
required = true
non_empty = true

[types.Target.fields.line]
type = "integer"
required = true
min = 1

[types.Fix]
type = "record"

[types.Fix.fields.tier]
type = "integer"
required = true
min = 1
max = 3

[types.Fix.fields.description]
type = "string"
required = true
non_empty = true
`,
}

const embeddedMainFile = "findings.schema.toml"

var program *strictspec.Program

func init() {
	// Version pairing: generated code and runtime must be the same release.
	strictspec.RequireRuntimeVersion(GeneratedBy)
	p, err := strictspec.CompileEmbedded(embeddedSchema, embeddedMainFile)
	if err != nil {
		panic(err)
	}
	program = p
}

// ValidateBytes is the raw-bytes entry point: lossless parse of input in the
// given syntax ("json" | "toml" | "jsonl"), then validate. It returns the
// typed root value (nil when any diagnostic fired) and the ordered diagnostics.
func ValidateBytes(input []byte, syntax string) (*Findings, []strictspec.Diagnostic) {
	res := program.Validate(input, syntax)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	v, err := strictspec.LoadValue(input, syntax)
	if err != nil {
		return nil, res.Diagnostics
	}
	return bindFindings(v), nil
}

// ValidateValue is the tagged-value entry point: validate an already-parsed
// tagged document value (from strictspec.LoadValue or a typed constructor).
func ValidateValue(v strictspec.Value) (*Findings, []strictspec.Diagnostic) {
	res := program.ValidateValue(v)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	return bindFindings(v), nil
}

// ValidateBytesWithEvidence is ValidateBytes plus cross-document resolver
// evidence for the phase-2 constraint vocabulary.
func ValidateBytesWithEvidence(input []byte, syntax string, evidence map[string][]map[string]any) (*Findings, []strictspec.Diagnostic) {
	res := program.ValidateWithEvidence(input, syntax, evidence)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	v, err := strictspec.LoadValue(input, syntax)
	if err != nil {
		return nil, res.Diagnostics
	}
	return bindFindings(v), nil
}

// Findings is the frozen typed binding of the "Findings" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type Findings struct {
	StrictcodeVersion string
	WorkspaceRoot     string
	Findings          []*Finding
}

func bindFindings(v strictspec.Value) *Findings {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &Findings{}
	if fv, ok := v.Field("strictcode_version"); ok {
		out.StrictcodeVersion = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("workspace_root"); ok {
		out.WorkspaceRoot = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("findings"); ok {
		out.Findings = bindSlice(fv, func(e strictspec.Value) *Finding { return bindFinding(e) })
	}
	return out
}

// WithStrictcodeVersion returns a copy of Findings with StrictcodeVersion set to the given value.
func (x *Findings) WithStrictcodeVersion(v string) *Findings {
	c := *x
	c.StrictcodeVersion = v
	return &c
}

// WithWorkspaceRoot returns a copy of Findings with WorkspaceRoot set to the given value.
func (x *Findings) WithWorkspaceRoot(v string) *Findings {
	c := *x
	c.WorkspaceRoot = v
	return &c
}

// WithFindings returns a copy of Findings with Findings set to the given value.
func (x *Findings) WithFindings(v []*Finding) *Findings {
	c := *x
	c.Findings = v
	return &c
}

// Finding is the frozen typed binding of the "Finding" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type Finding struct {
	Rule     string
	Severity string
	Message  string
	Target   *Target
	Fix      *Fix
}

func bindFinding(v strictspec.Value) *Finding {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &Finding{}
	if fv, ok := v.Field("rule"); ok {
		out.Rule = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("severity"); ok {
		out.Severity = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("message"); ok {
		out.Message = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("target"); ok {
		out.Target = bindTarget(fv)
	}
	if fv, ok := v.Field("fix"); ok {
		out.Fix = bindFix(fv)
	}
	return out
}

// WithRule returns a copy of Finding with Rule set to the given value.
func (x *Finding) WithRule(v string) *Finding {
	c := *x
	c.Rule = v
	return &c
}

// WithSeverity returns a copy of Finding with Severity set to the given value.
func (x *Finding) WithSeverity(v string) *Finding {
	c := *x
	c.Severity = v
	return &c
}

// WithMessage returns a copy of Finding with Message set to the given value.
func (x *Finding) WithMessage(v string) *Finding {
	c := *x
	c.Message = v
	return &c
}

// WithTarget returns a copy of Finding with Target set to the given value.
func (x *Finding) WithTarget(v *Target) *Finding {
	c := *x
	c.Target = v
	return &c
}

// WithFix returns a copy of Finding with Fix set to the given value.
func (x *Finding) WithFix(v *Fix) *Finding {
	c := *x
	c.Fix = v
	return &c
}

// Target is the frozen typed binding of the "Target" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type Target struct {
	Id   string
	Kind string
	File string
	Line int64
}

func bindTarget(v strictspec.Value) *Target {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &Target{}
	if fv, ok := v.Field("id"); ok {
		out.Id = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("kind"); ok {
		out.Kind = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("file"); ok {
		out.File = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("line"); ok {
		out.Line = func() int64 { r, _ := fv.Int(); return r }()
	}
	return out
}

// WithId returns a copy of Target with Id set to the given value.
func (x *Target) WithId(v string) *Target {
	c := *x
	c.Id = v
	return &c
}

// WithKind returns a copy of Target with Kind set to the given value.
func (x *Target) WithKind(v string) *Target {
	c := *x
	c.Kind = v
	return &c
}

// WithFile returns a copy of Target with File set to the given value.
func (x *Target) WithFile(v string) *Target {
	c := *x
	c.File = v
	return &c
}

// WithLine returns a copy of Target with Line set to the given value.
func (x *Target) WithLine(v int64) *Target {
	c := *x
	c.Line = v
	return &c
}

// Fix is the frozen typed binding of the "Fix" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type Fix struct {
	Tier        int64
	Description string
}

func bindFix(v strictspec.Value) *Fix {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &Fix{}
	if fv, ok := v.Field("tier"); ok {
		out.Tier = func() int64 { r, _ := fv.Int(); return r }()
	}
	if fv, ok := v.Field("description"); ok {
		out.Description = func() string { r, _ := fv.AsString(); return r }()
	}
	return out
}

// WithTier returns a copy of Fix with Tier set to the given value.
func (x *Fix) WithTier(v int64) *Fix {
	c := *x
	c.Tier = v
	return &c
}

// WithDescription returns a copy of Fix with Description set to the given value.
func (x *Fix) WithDescription(v string) *Fix {
	c := *x
	c.Description = v
	return &c
}

func bindSlice[T any](v strictspec.Value, f func(strictspec.Value) T) []T {
	items := v.Items()
	out := make([]T, len(items))
	for i, e := range items {
		out[i] = f(e)
	}
	return out
}

func bindPtr[T any](v strictspec.Value, f func(strictspec.Value) T) *T {
	if v.IsNull() {
		return nil
	}
	t := f(v)
	return &t
}
