// Code generated by strictspec. DO NOT EDIT.
//
// strictspec generator: 0.1.0
// schema:              strictcode-config (format_version 1)
// regenerate:          strictspec gen --manifest strictspec.toml
//
// Released under the MIT license (unencumbered). This file is machine-generated;
// edit the schema and regenerate, never this file.
package configspec

import "github.com/smm-h/strictspec/go/strictspec"

// GeneratedBy is the strictspec release that produced this file. The runtime
// pairing guard hard-errors unless it matches the linked runtime exactly.
const GeneratedBy = "0.1.0"

// SchemaFormatVersion is the document format_version this validator accepts.
const SchemaFormatVersion = 1

// embeddedSchema carries the compiled schema (and its imported type-definition
// files and scalar manifest) so the validator is self-contained and does no IO.
var embeddedSchema = map[string]string{
	"config.schema.toml": `name = "strictcode-config"
meta_version = 1
format_version = 1
document_syntax = "toml"
role = "schema"
root = "Config"
targets = ["go"]
description = "Gates strictcode.toml: the single configuration file (DESIGN.md section 12.3) — rule toggles/severities/thresholds, analysis modes, group toggles, and per-rule-shaped suppressions with mandatory reasons. Rule-ID validity (including tombstone rendering) and suppression-shape-vs-rule matching are consumer-native checks against the registry; path staleness is the stale-suppression rule."

[types.Config]
type = "record"

[types.Config.fields.analysis]
type = "Analysis"
required = false

[types.Config.fields.groups]
type = "map"
required = false
key_pattern = "^[a-z][a-z0-9-]*$"
order = "incidental"
[types.Config.fields.groups.value]
type = "GroupConfig"

[types.Config.fields.rules]
type = "map"
required = false
key_pattern = "^[a-z][a-z0-9]*(-[a-z0-9]+)*$"
order = "incidental"
[types.Config.fields.rules.value]
type = "RuleConfig"

[types.Analysis]
type = "record"
description = "Explicit analysis-mode selection. The presence of a mode key IS the choice; a configured mode that cannot run is a hard error, never a downgrade."

[types.Analysis.fields.python_call_resolution]
type = "enum"
required = false
values = ["syntactic", "type-checker"]
description = "Python call-resolution layer (DESIGN.md section 8). Absent = the always-on syntactic layer only; type-checker requires python_type_checker."

[types.Analysis.fields.python_type_checker]
type = "enum"
required = false
values = ["pyright", "ty"]
description = "Which external type checker backs type-checker mode. Mandatory with python_call_resolution = type-checker; forbidden with syntactic."

[[types.Analysis.constraints]]
form = "conditional-required"
field = "python_type_checker"
when = { field = "python_call_resolution", predicate = "equals", value = "type-checker" }

[[types.Analysis.constraints]]
form = "forbidden-when"
field = "python_type_checker"
when = { field = "python_call_resolution", predicate = "equals", value = "syntactic" }

[types.GroupConfig]
type = "record"
description = "A group toggle (group:<name>): enable/disable or re-severity every member rule in one stroke."

[types.GroupConfig.fields.enabled]
type = "boolean"
required = false

[types.GroupConfig.fields.severity]
type = "enum"
required = false
values = ["error", "warning"]

[[types.GroupConfig.constraints]]
form = "at-least-one-of"
fields = ["enabled", "severity"]

[types.RuleConfig]
type = "record"

[types.RuleConfig.fields.enabled]
type = "boolean"
required = false

[types.RuleConfig.fields.severity]
type = "enum"
required = false
values = ["error", "warning"]

[types.RuleConfig.fields.thresholds]
type = "map"
required = false
key_pattern = "^[a-z][a-z0-9_-]*$"
order = "incidental"
description = "Named integer thresholds for rules that declare them (wave-two rules; no v1 seed rule has thresholds)."
[types.RuleConfig.fields.thresholds.value]
type = "integer"

[types.RuleConfig.fields.suppressions]
type = "array"
required = false
[types.RuleConfig.fields.suppressions.item]
type = "Suppression"

[types.RuleConfig.fields.allow]
type = "map"
required = false
key_pattern = "^(py|go|ts)$"
order = "incidental"
description = "Per-language allow lists (library-forbidden-imports): entries subtracted from the effective forbidden set, merged with the workspace-level lint_allow list."
[types.RuleConfig.fields.allow.value]
type = "array"
[types.RuleConfig.fields.allow.value.item]
type = "string"
non_empty = true

[types.RuleConfig.fields.forbidden]
type = "map"
required = false
key_pattern = "^(py|go|ts)$"
order = "incidental"
description = "Per-language replacement of the default forbidden-imports list."
[types.RuleConfig.fields.forbidden.value]
type = "array"
[types.RuleConfig.fields.forbidden.value.item]
type = "string"
non_empty = true

[types.Suppression]
type = "record"
description = "One suppression in the rule's natural target shape: path | (project, dep) | modules (cycle member set) | member. The reason is mandatory and non-empty; shape-vs-rule matching is a consumer-native check against the registry."

[types.Suppression.fields.reason]
type = "string"
required = true
non_empty = true

[types.Suppression.fields.path]
type = "string"
required = false
non_empty = true
description = "A file path (Python, TS/JS) or package directory (Go), relative to the project root."

[types.Suppression.fields.project]
type = "string"
required = false
non_empty = true

[types.Suppression.fields.dep]
type = "string"
required = false
non_empty = true

[types.Suppression.fields.modules]
type = "array"
required = false
min_len = 2
description = "The set of modules forming one reported import cycle (an SCC has at least two members)."
[types.Suppression.fields.modules.item]
type = "string"
non_empty = true

[types.Suppression.fields.member]
type = "string"
required = false
non_empty = true
description = "A workspace member name."

[[types.Suppression.constraints]]
form = "exactly-one-of"
fields = ["path", "dep", "modules", "member"]

[[types.Suppression.constraints]]
form = "co-presence"
fields = ["project", "dep"]
`,
}

const embeddedMainFile = "config.schema.toml"

var program *strictspec.Program

func init() {
	// Version pairing: generated code and runtime must be the same release.
	strictspec.RequireRuntimeVersion(GeneratedBy)
	p, err := strictspec.CompileEmbedded(embeddedSchema, embeddedMainFile)
	if err != nil {
		panic(err)
	}
	program = p
}

// ValidateBytes is the raw-bytes entry point: lossless parse of input in the
// given syntax ("json" | "toml" | "jsonl"), then validate. It returns the
// typed root value (nil when any diagnostic fired) and the ordered diagnostics.
func ValidateBytes(input []byte, syntax string) (*Config, []strictspec.Diagnostic) {
	res := program.Validate(input, syntax)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	v, err := strictspec.LoadValue(input, syntax)
	if err != nil {
		return nil, res.Diagnostics
	}
	return bindConfig(v), nil
}

// ValidateValue is the tagged-value entry point: validate an already-parsed
// tagged document value (from strictspec.LoadValue or a typed constructor).
func ValidateValue(v strictspec.Value) (*Config, []strictspec.Diagnostic) {
	res := program.ValidateValue(v)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	return bindConfig(v), nil
}

// ValidateBytesWithEvidence is ValidateBytes plus cross-document resolver
// evidence for the phase-2 constraint vocabulary.
func ValidateBytesWithEvidence(input []byte, syntax string, evidence map[string][]map[string]any) (*Config, []strictspec.Diagnostic) {
	res := program.ValidateWithEvidence(input, syntax, evidence)
	if !res.Valid {
		return nil, res.Diagnostics
	}
	v, err := strictspec.LoadValue(input, syntax)
	if err != nil {
		return nil, res.Diagnostics
	}
	return bindConfig(v), nil
}

// Config is the frozen typed binding of the "Config" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type Config struct {
	Analysis *Analysis
	Groups   strictspec.Value
	Rules    strictspec.Value
}

func bindConfig(v strictspec.Value) *Config {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &Config{}
	if fv, ok := v.Field("analysis"); ok {
		out.Analysis = bindAnalysis(fv)
	}
	if fv, ok := v.Field("groups"); ok {
		out.Groups = fv
	}
	if fv, ok := v.Field("rules"); ok {
		out.Rules = fv
	}
	return out
}

// WithAnalysis returns a copy of Config with Analysis set to the given value.
func (x *Config) WithAnalysis(v *Analysis) *Config {
	c := *x
	c.Analysis = v
	return &c
}

// WithGroups returns a copy of Config with Groups set to the given value.
func (x *Config) WithGroups(v strictspec.Value) *Config {
	c := *x
	c.Groups = v
	return &c
}

// WithRules returns a copy of Config with Rules set to the given value.
func (x *Config) WithRules(v strictspec.Value) *Config {
	c := *x
	c.Rules = v
	return &c
}

// Analysis is the frozen typed binding of the "Analysis" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type Analysis struct {
	PythonCallResolution string
	PythonTypeChecker    string
}

func bindAnalysis(v strictspec.Value) *Analysis {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &Analysis{}
	if fv, ok := v.Field("python_call_resolution"); ok {
		out.PythonCallResolution = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("python_type_checker"); ok {
		out.PythonTypeChecker = func() string { r, _ := fv.AsString(); return r }()
	}
	return out
}

// WithPythonCallResolution returns a copy of Analysis with PythonCallResolution set to the given value.
func (x *Analysis) WithPythonCallResolution(v string) *Analysis {
	c := *x
	c.PythonCallResolution = v
	return &c
}

// WithPythonTypeChecker returns a copy of Analysis with PythonTypeChecker set to the given value.
func (x *Analysis) WithPythonTypeChecker(v string) *Analysis {
	c := *x
	c.PythonTypeChecker = v
	return &c
}

// GroupConfig is the frozen typed binding of the "GroupConfig" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type GroupConfig struct {
	Enabled  bool
	Severity string
}

func bindGroupConfig(v strictspec.Value) *GroupConfig {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &GroupConfig{}
	if fv, ok := v.Field("enabled"); ok {
		out.Enabled = func() bool { r, _ := fv.Bool(); return r }()
	}
	if fv, ok := v.Field("severity"); ok {
		out.Severity = func() string { r, _ := fv.AsString(); return r }()
	}
	return out
}

// WithEnabled returns a copy of GroupConfig with Enabled set to the given value.
func (x *GroupConfig) WithEnabled(v bool) *GroupConfig {
	c := *x
	c.Enabled = v
	return &c
}

// WithSeverity returns a copy of GroupConfig with Severity set to the given value.
func (x *GroupConfig) WithSeverity(v string) *GroupConfig {
	c := *x
	c.Severity = v
	return &c
}

// RuleConfig is the frozen typed binding of the "RuleConfig" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type RuleConfig struct {
	Enabled      bool
	Severity     string
	Thresholds   strictspec.Value
	Suppressions []*Suppression
	Allow        strictspec.Value
	Forbidden    strictspec.Value
}

func bindRuleConfig(v strictspec.Value) *RuleConfig {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &RuleConfig{}
	if fv, ok := v.Field("enabled"); ok {
		out.Enabled = func() bool { r, _ := fv.Bool(); return r }()
	}
	if fv, ok := v.Field("severity"); ok {
		out.Severity = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("thresholds"); ok {
		out.Thresholds = fv
	}
	if fv, ok := v.Field("suppressions"); ok {
		out.Suppressions = bindSlice(fv, func(e strictspec.Value) *Suppression { return bindSuppression(e) })
	}
	if fv, ok := v.Field("allow"); ok {
		out.Allow = fv
	}
	if fv, ok := v.Field("forbidden"); ok {
		out.Forbidden = fv
	}
	return out
}

// WithEnabled returns a copy of RuleConfig with Enabled set to the given value.
func (x *RuleConfig) WithEnabled(v bool) *RuleConfig {
	c := *x
	c.Enabled = v
	return &c
}

// WithSeverity returns a copy of RuleConfig with Severity set to the given value.
func (x *RuleConfig) WithSeverity(v string) *RuleConfig {
	c := *x
	c.Severity = v
	return &c
}

// WithThresholds returns a copy of RuleConfig with Thresholds set to the given value.
func (x *RuleConfig) WithThresholds(v strictspec.Value) *RuleConfig {
	c := *x
	c.Thresholds = v
	return &c
}

// WithSuppressions returns a copy of RuleConfig with Suppressions set to the given value.
func (x *RuleConfig) WithSuppressions(v []*Suppression) *RuleConfig {
	c := *x
	c.Suppressions = v
	return &c
}

// WithAllow returns a copy of RuleConfig with Allow set to the given value.
func (x *RuleConfig) WithAllow(v strictspec.Value) *RuleConfig {
	c := *x
	c.Allow = v
	return &c
}

// WithForbidden returns a copy of RuleConfig with Forbidden set to the given value.
func (x *RuleConfig) WithForbidden(v strictspec.Value) *RuleConfig {
	c := *x
	c.Forbidden = v
	return &c
}

// Suppression is the frozen typed binding of the "Suppression" record. Fields are immutable by
// convention (shallow-plus-generated-immutability); use With* for copy-on-write.
type Suppression struct {
	Reason  string
	Path    string
	Project string
	Dep     string
	Modules []string
	Member  string
}

func bindSuppression(v strictspec.Value) *Suppression {
	if v.Kind() != strictspec.KindRecord {
		return nil
	}
	out := &Suppression{}
	if fv, ok := v.Field("reason"); ok {
		out.Reason = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("path"); ok {
		out.Path = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("project"); ok {
		out.Project = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("dep"); ok {
		out.Dep = func() string { r, _ := fv.AsString(); return r }()
	}
	if fv, ok := v.Field("modules"); ok {
		out.Modules = bindSlice(fv, func(e strictspec.Value) string { return func() string { r, _ := e.AsString(); return r }() })
	}
	if fv, ok := v.Field("member"); ok {
		out.Member = func() string { r, _ := fv.AsString(); return r }()
	}
	return out
}

// WithReason returns a copy of Suppression with Reason set to the given value.
func (x *Suppression) WithReason(v string) *Suppression {
	c := *x
	c.Reason = v
	return &c
}

// WithPath returns a copy of Suppression with Path set to the given value.
func (x *Suppression) WithPath(v string) *Suppression {
	c := *x
	c.Path = v
	return &c
}

// WithProject returns a copy of Suppression with Project set to the given value.
func (x *Suppression) WithProject(v string) *Suppression {
	c := *x
	c.Project = v
	return &c
}

// WithDep returns a copy of Suppression with Dep set to the given value.
func (x *Suppression) WithDep(v string) *Suppression {
	c := *x
	c.Dep = v
	return &c
}

// WithModules returns a copy of Suppression with Modules set to the given value.
func (x *Suppression) WithModules(v []string) *Suppression {
	c := *x
	c.Modules = v
	return &c
}

// WithMember returns a copy of Suppression with Member set to the given value.
func (x *Suppression) WithMember(v string) *Suppression {
	c := *x
	c.Member = v
	return &c
}

func bindSlice[T any](v strictspec.Value, f func(strictspec.Value) T) []T {
	items := v.Items()
	out := make([]T, len(items))
	for i, e := range items {
		out[i] = f(e)
	}
	return out
}

func bindPtr[T any](v strictspec.Value, f func(strictspec.Value) T) *T {
	if v.IsNull() {
		return nil
	}
	t := f(v)
	return &t
}
